<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_groupactivity.php by Valery Votintsev at sources.ru
 */

$lang = array
(
	'groupactivity_fids'			=> 'Форум',
	'groupactivity_fids_comment'		=> 'Вы можете выбрать несколько значений, удерживая клавишу CTRL. Если ничего не выбрано - без ограничений',
	'groupactivity_gtids'			=> 'Категория гуппы',
	'groupactivity_gtids_comment'		=> 'Вы можете выбрать несколько значений, удерживая клавишу CTRL. Если ничего не выбрано - без ограничений',
	'groupactivity_uids'			=> 'UID пользователя',
	'groupactivity_uids_comment'		=> 'Для нескольких значений, используйте запятую с пробелом',
	'groupactivity_startrow'		=> 'Первоначальное количество строк',
	'groupactivity_startrow_comment'	=> 'Чтобы задать начальное количество строк, введите значения. Например: 0, чтобы начать с первой линии и так далее...',
	'groupactivity_items'			=> 'Отображение количества записей в статьях',
	'groupactivity_items_comment'		=> 'Отображение количества записей в статьях. Установите целое число, больше 0',
	'groupactivity_titlelength'		=> 'Максимальное количество байт в названии',
	'groupactivity_titlelength_comment'	=> 'Настройка длинны символов заголовка. Если заголовок больше указанного значения, длинна названия будет автоматически урезана до указанного значения. Если - 0, не урезать',
	'groupactivity_fnamelength'		=> 'Название форума содержит максимальное количество байт',
	'groupactivity_fnamelength_comment'	=> 'Укажите необходимые значения',
	'groupactivity_summarylength'		=> 'Анонс (краткое содержание) темы',
	'groupactivity_summarylength_comment'	=> 'Установить значение для текста, используйте значение по умолчанию от 0 до 255',
	'groupactivity_tids'			=> 'Указание тем',
	'groupactivity_tids_comment'		=> 'Укажите tid тем, если несколько tid укажите их через запятую. Оставьте пустым, чтобы использовать без фильтра',
	'groupactivity_keyword'			=> 'Ключевое слово заглавия',
	'groupactivity_keyword_comment'		=> 'Задать ключевые слова для заголовка. Оставьте пустым, чтобы использовать без фильтра. В ключевых слова можно использовать символ: *',
	'groupactivity_typeids'			=> 'Категории тем',
	'groupactivity_typeids_comment'		=> 'Установите категории для тем. Оставьте пустым, чтобы использовать без фильтра',
	'groupactivity_typeids_all'		=> 'Все категории тем',
	'groupactivity_sortids'			=> 'Информация о категории',
	'groupactivity_sortids_comment'		=> 'Установить тему секретной информации. Оставьте пустым, чтобы использовать без фильтра',
	'groupactivity_sortids_all'		=> 'Все',
	'groupactivity_digest'			=> 'Дайджест тем',
	'groupactivity_digest_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'groupactivity_digest_0'		=> 'Общие темы',
	'groupactivity_digest_1'		=> 'Дайджест I',
	'groupactivity_digest_2'		=> 'Дайджест II',
	'groupactivity_digest_3'		=> 'Дайджест III',
	'groupactivity_stick'			=> 'Важная тема',
	'groupactivity_stick_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'groupactivity_stick_0'			=> 'Общие темы',
	'groupactivity_stick_1'			=> 'Топ I',
	'groupactivity_stick_2'			=> 'Топ II',
	'groupactivity_stick_3'			=> 'Топ III',
	'groupactivity_special'			=> 'Специальные темы',
	'groupactivity_special_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'groupactivity_special_1'		=> 'Темы опросов',
	'groupactivity_special_2'		=> 'Темы товаров',
	'groupactivity_special_3'		=> 'Темы платные',
	'groupactivity_special_4'		=> 'Темы событий',
	'groupactivity_special_5'		=> 'Темы поединков',
	'groupactivity_special_0'		=> 'Все темы',
	'groupactivity_special_reward'		=> 'Фильтр тем наград',
	'groupactivity_special_reward_comment'	=> 'Установить для темы определенный тип награды',
	'groupactivity_special_reward_0'	=> 'Все',
	'groupactivity_special_reward_1'	=> 'Выданные',
	'groupactivity_special_reward_2'	=> 'Не выданные',
	'groupactivity_recommend'		=> 'Фильтр рекомендуемых тем',
	'groupactivity_recommend_comment'	=> 'Укажите параметры рекомендуемых тем',
	'groupactivity_orderby'			=> 'Сортировка событий',
	'groupactivity_orderby_comment'		=> 'Настройка фильтра сортировки',
	'groupactivity_orderby_lastpost'	=> 'По дате создания',
	'groupactivity_orderby_dateline'	=> 'По дате сроку действия',
	'groupactivity_orderby_replies'		=> 'По числу ответов',
	'groupactivity_orderby_views'		=> 'По просмотрам',
	'groupactivity_orderby_heats'		=> 'По популярности',
	'groupactivity_orderby_recommends'	=> 'По рекомендациям',
	'groupactivity_orderby_hourviews'	=> 'По просмотрам в течении часа',
	'groupactivity_orderby_todayviews'	=> 'По просмотрам в течении дня',
	'groupactivity_orderby_weekviews'	=> 'По просмотрам в течении недели',
	'groupactivity_orderby_monthviews'	=> 'По просмотрам в течении месяца',
	'groupactivity_orderby_hours'		=> 'По заданному времени (по часам)',
	'groupactivity_orderby_hours_comment'	=> 'Просмотр в течение указанного времени',
	'groupactivity_orderby_todayhots'	=> 'Общее количество продаж за сегодня',
	'groupactivity_orderby_weekhots'	=> 'Общее количество продаж за неделю',
	'groupactivity_orderby_monthhots'	=> 'Общее количество продаж за месяц',
	'groupactivity_price_add'		=> 'Дополнительно',
	'groupactivity_place'			=> 'Место события',
	'groupactivity_class'			=> 'Тип события',
	'groupactivity_class_all'		=> 'Все типы',
	'groupactivity_gender'			=> 'Пол',
	'groupactivity_gender_0'		=> 'Неизвестно',
	'groupactivity_gender_1'		=> 'муж',
	'groupactivity_gender_2'		=> 'жен',
	'groupactivity_orderby_weekstart'	=> 'Начало события за неделю',
	'groupactivity_orderby_monthstart'	=> 'Начало события за месяц',
	'groupactivity_orderby_weekexp'		=> 'Окончание приема заявок за неделю',
	'groupactivity_orderby_monthexp'	=> 'Окончание приема заявок за месяц',
	'groupactivity_gviewperm'		=> 'Обзор разрешений групп',
	'groupactivity_gviewperm_nolimit'	=> 'Без ограничений',
	'groupactivity_gviewperm_only_member'	=> 'Только для членов',
	'groupactivity_gviewperm_all_member'	=> 'Все',
	'groupactivity_highlight'		=> 'Выделение значений', 
);

?>