<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_grouptrade.php by Valery Votintsev at sources.ru
 */

$lang = array
(
	'grouptrade_fids'			=> 'Указанная группа',
	'grouptrade_fids_comment'		=> 'Укажите группы, которые могут участвовать. Вы можете выбрать несколько значений, для этого удерживайте клавишу CTRL',
	'grouptrade_gtids'			=> 'Категория гуппы',
	'grouptrade_gtids_comment'		=> 'Вы можете выбрать несколько значений, удерживая клавишу CTRL. Если ничего не выбрано - без ограничений',
	'grouptrade_uids'			=> 'UID пользователя',
	'grouptrade_uids_comment'		=> 'Для нескольких значений, используйте запятую с пробелом',
	'grouptrade_startrow'			=> 'Первоначальное количество строк',
	'grouptrade_startrow_comment'		=> 'Чтобы задать начальное количество строк, введите значения. Например: 0, чтобы начать с первой линии и так далее...',
	'grouptrade_items'			=> 'Отображение количества записей в статьях',
	'grouptrade_items_comment'		=> 'Отображение количества записей в статьях. Установите целое число, больше 0',
	'grouptrade_titlelength'		=> 'Максимальное количество байт в названии',
	'grouptrade_titlelength_comment'	=> 'Настройка длинны символов заголовка. Если заголовок больше указанного значения, длинна названия будет автоматически урезана до указанного значения. Если - 0, не урезать',
	'grouptrade_fnamelength'		=> 'Название форума содержит максимальное количество байт',
	'grouptrade_fnamelength_comment'	=> 'Укажите необходимые значения',
	'grouptrade_summarylength'		=> 'Анонс (краткое содержание) темы',
	'grouptrade_summarylength_comment'	=> 'Установить значение для текста, используйте значение по умолчанию от 0 до 255',
	'grouptrade_tids'			=> 'Указание тем',
	'grouptrade_tids_comment'		=> 'Укажите tid тем, если несколько tid укажите их через запятую. Оставьте пустым, чтобы использовать без фильтра',
	'grouptrade_keyword'			=> 'Ключевое слово заглавия',
	'grouptrade_keyword_comment'		=> 'Задать ключевые слова для заголовка. Оставьте пустым, чтобы использовать без фильтра. В ключевых слова можно использовать символ: *',
	'grouptrade_typeids'			=> 'Категории тем',
	'grouptrade_typeids_comment'		=> 'Установите категории для тем. Оставьте пустым, чтобы использовать без фильтра',
	'grouptrade_typeids_all'		=> 'Все категории тем',
	'grouptrade_sortids'			=> 'Информация о категории',
	'grouptrade_sortids_comment'		=> 'Установить тему секретной информации. Оставьте пустым, чтобы использовать без фильтра',
	'grouptrade_sortids_all'		=> 'Все',
	'grouptrade_digest'			=> 'Дайджест тем',
	'grouptrade_digest_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'grouptrade_digest_0'			=> 'Общие темы',
	'grouptrade_digest_1'			=> 'Дайджест I',
	'grouptrade_digest_2'			=> 'Дайджест II',
	'grouptrade_digest_3'			=> 'Дайджест III',
	'grouptrade_stick'			=> 'Важная тема',
	'grouptrade_stick_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'grouptrade_stick_0'			=> 'Общие темы',
	'grouptrade_stick_1'			=> 'Топ I',
	'grouptrade_stick_2'			=> 'Топ II',
	'grouptrade_stick_3'			=> 'Топ III',
	'grouptrade_special'			=> 'Специальные темы',
	'grouptrade_special_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'grouptrade_special_1'			=> 'Темы опросов',
	'grouptrade_special_2'			=> 'Темы товаров',
	'grouptrade_special_3'			=> 'Темы платные',
	'grouptrade_special_4'			=> 'Темы событий',
	'grouptrade_special_5'			=> 'Темы поединков',
	'grouptrade_special_0'			=> 'Все темы',
	'grouptrade_special_reward'		=> 'Фильтр тем наград',
	'grouptrade_special_reward_comment'	=> 'Установить для темы определенный тип награды',
	'grouptrade_special_reward_0'		=> 'Все',
	'grouptrade_special_reward_1'		=> 'Выданные',
	'grouptrade_special_reward_2'		=> 'Не выданные',
	'grouptrade_recommend'			=> 'Фильтр рекомендуемых тем',
	'grouptrade_recommend_comment'		=> 'Укажите параметры рекомендуемых тем',
	'grouptrade_orderby'			=> 'Сортировка тем',
	'grouptrade_orderby_comment'		=> 'Настройка фильтра сортировки',
	'grouptrade_orderby_lastpost'		=> 'По дате создания',
	'grouptrade_orderby_dateline'		=> 'По дате сроку действия',
	'grouptrade_orderby_replies'		=> 'По числу ответов',
	'grouptrade_orderby_views'		=> 'По просмотрам',
	'grouptrade_orderby_heats'		=> 'По популярности',
	'grouptrade_orderby_recommends'		=> 'По рекомендациям',
	'grouptrade_orderby_hourviews'		=> 'По просмотрам в течении часа',
	'grouptrade_orderby_todayviews'		=> 'По просмотрам в течении дня',
	'grouptrade_orderby_weekviews'		=> 'По просмотрам в течении недели',
	'grouptrade_orderby_monthviews'		=> 'По просмотрам в течении месяца',
	'grouptrade_orderby_hours'		=> 'По заданному времени (по часам)',
	'grouptrade_orderby_hours_comment'	=> 'Просмотр в течение указанного времени',
	'grouptrade_orderby_todayhots'		=> 'Общее количество продаж за сегодня',
	'grouptrade_orderby_weekhots'		=> 'Общее количество продаж за неделю',
	'grouptrade_orderby_monthhots'		=> 'Общее количество продаж за месяц',
	'grouptrade_price_add'			=> 'Дополнительно',
	'grouptrade_place'			=> 'Место события',
	'grouptrade_class'			=> 'Тип события',
	'grouptrade_gender'			=> 'Пол',
	'grouptrade_gender_0'			=> 'Неизвестно',
	'grouptrade_gender_1'			=> 'муж',
	'grouptrade_gender_2'			=> 'жен',
	'grouptrade_orderby_weekstart'		=> 'Начало события за неделю',
	'grouptrade_orderby_monthstart'		=> 'Начало события за месяц',
	'grouptrade_orderby_weekexp'		=> 'Окончание приема заявок за неделю',
	'grouptrade_orderby_monthexp'		=> 'Окончание приема заявок за месяц',
	'grouptrade_gviewperm'			=> 'Обзор разрешений групп',
	'grouptrade_gviewperm_nolimit'		=> 'Без ограничений',
	'grouptrade_gviewperm_only_member'	=> 'Только для членов',
	'grouptrade_gviewperm_all_member'	=> 'Все',
	'grouptrade_highlight'			=> 'Выделить значение', 
);

