<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_categorylist.php by Valery Votintsev at sources.ru
 */

$lang = array
(
	'categorylist_fids'			=> 'Форум',
	'categorylist_fids_comment'		=> 'Вы можете выбрать несколько значений, удерживая клавишу CTRL. Если ничего не выбрано - без ограничений',
	'categorylist_startrow'			=> 'Первоначальное количество строк',
	'categorylist_startrow_comment'		=> 'Чтобы задать начальное количество строк, введите значения. Например: 0, чтобы начать с первой линии и так далее...',
	'categorylist_showitems'		=> 'Показ количества статей',
	'categorylist_showitems_comment'	=> 'Показ количества статей. Укажите число больше 0',
	'categorylist_titlelength'		=> 'Максимальное количество байт в названии',
	'categorylist_titlelength_comment'	=> 'Настройка длинны символов заголовка. Если заголовок больше указанного значения, длинна названия будет автоматически урезана до указанного значения. Если - 0, не урезать',
	'categorylist_fnamelength'		=> 'Название форума содержит максимальное количество байт',
	'categorylist_fnamelength_comment'	=> 'Укажите необходимые значения',
	'categorylist_summarylength'		=> 'Анонс (краткое содержание) темы',
	'categorylist_summarylength_comment'	=> 'Установить значение для текста, используйте значение по умолчанию от 0 до 255',
	'categorylist_tids'			=> 'Указание тем',
	'categorylist_tids_comment'		=> 'Укажите tid тем, если несколько tid укажите их через запятую. Оставьте пустым, чтобы использовать без фильтра',
	'categorylist_keyword'			=> 'Ключевое слово заглавия',
	'categorylist_keyword_comment'		=> 'Задать ключевые слова для заголовка. Оставьте пустым, чтобы использовать без фильтра. В ключевых слова можно использовать символ: *',
	'categorylist_sortids'			=> 'Информация о категории',
	'categorylist_sortids_comment'		=> 'Установить тему секретной информации. Оставьте пустым, чтобы использовать без фильтра',
	'categorylist_styleids'			=> 'Категории шаблонов',
	'categorylist_styleids_comment'		=> 'Укажите категории шаблонов',
	'categorylist_styleids_style1'		=> 'Вариант 1',
	'categorylist_styleids_style2'		=> 'Вариант 2',
	'categorylist_styleids_style3'		=> 'Вариант 3',
	'categorylist_styleids_style4'		=> 'Вариант 4',
	'categorylist_styleids_style5'		=> 'Вариант 5',
	'categorylist_typeids_all'		=> 'Все категории тем',
	'categorylist_categoryids'		=> 'Категории',
	'categorylist_categoryids_comment'	=> 'Выберите категории',
	'categorylist_categoryids_all'		=> 'Все',
	'categorylist_digest'			=> 'Дайджест тем',
	'categorylist_digest_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'categorylist_digest_0'			=> 'Общие темы',
	'categorylist_digest_1'			=> 'Дайджест I',
	'categorylist_digest_2'			=> 'Дайджест II',
	'categorylist_digest_3'			=> 'Дайджест III',
	'categorylist_stick'			=> 'Важная тема',
	'categorylist_stick_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'categorylist_stick_0'			=> 'Общие темы',
	'categorylist_stick_1'			=> 'Топ I',
	'categorylist_stick_2'			=> 'Топ II',
	'categorylist_stick_3'			=> 'Топ III',
	'categorylist_special'			=> 'Специальные темы',
	'categorylist_special_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'categorylist_special_1'		=> 'Темы опросов',
	'categorylist_special_2'		=> 'Темы товаров',
	'categorylist_special_3'		=> 'Темы платные',
	'categorylist_special_4'		=> 'Темы событий',
	'categorylist_special_5'		=> 'Темы поединков',
	'categorylist_special_0'		=> 'Все темы',
	'categorylist_special_reward'		=> 'Фильтр тем наград',
	'categorylist_special_reward_comment'	=> 'Установить для темы определенный тип награды',
	'categorylist_special_reward_0'		=> 'Все',
	'categorylist_special_reward_1'		=> 'Выданные',
	'categorylist_special_reward_2'		=> 'Не выданные',
	'categorylist_recommend'		=> 'Фильтр рекомендуемых тем',
	'categorylist_recommend_comment'	=> 'Укажите параметры рекомендуемых тем',
	'categorylist_orderby'			=> 'Сортировка тем',
	'categorylist_orderby_comment'		=> 'Настройка фильтра сортировки',
	'categorylist_orderby_lastpost'		=> 'По дате создания',
	'categorylist_orderby_dateline'		=> 'По дате сроку действия',
	'categorylist_orderby_replies'		=> 'По числу ответов',
	'categorylist_orderby_views'		=> 'По просмотрам',
	'categorylist_orderby_heats'		=> 'По популярности',
	'categorylist_orderby_recommends'	=> 'По рекомендациям',
	'categorylist_orderby_hourviews'	=> 'По просмотрам в течении часа',
	'categorylist_orderby_todayviews'	=> 'По просмотрам в течении дня',
	'categorylist_orderby_weekviews'	=> 'По просмотрам в течении недели',
	'categorylist_orderby_monthviews'	=> 'По просмотрам в течении месяца',
	'categorylist_orderby_hours'		=> 'По заданному времени (по часам)',
	'categorylist_orderby_hours_comment'	=> 'Просмотр в течение указанного времени',
);

