<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_core.php by Khalid Nahhal, http://www.ar-discuz.com
 *      Modified by Valery Votintsev at sources.ru
 */

 
$lang = array
(
	'nextpage'	=> 'التالي',//'下一页',
	'prevpage'	=> 'السابق',//'上一页',
	'date'	=> array(
		'before'	=> 'قبل ',//'前',
		'day'		=> 'يوم ',//'天',
		'yday'		=> 'أمس ',//'昨天',
		'byday'		=> 'أول أمس',//'前天',
		'hour'		=> 'ساعة ',//'小时',
		'half'		=> 'نصف ',//'半',
		'min'		=> 'دقيقة ',//'分钟',
		'sec'		=> 'ثانية ',//'秒',
		'now'		=> 'الآن ',//'刚刚',
	),
	'yes'			=> 'نعم',//'是',
	'no'			=> 'لا',//'否',
	'weeks'	=> array(
		1 => 'الاثنين',//'周一',
		2 => 'الثلاثاء',//'周二',
		3 => 'الاربعاء',//'周三',
		4 => 'الخميس',//'周四',
		5 => 'الجمعة',//'周五',
		6 => 'السبت',//'周六',
		7 => 'الاحد',//'周日',
	),
	'dot'	 	=> '. ',//'、',//!!!!!!!!!! Have to add spaces ?????????
	'archive'	=> 'الارشيف',//'存档',
	'portal' 	=> 'المجلة',//'文章',
	'end'	 	=> 'النهاية',//'末尾',

	'seccode_image_tips'		=> 'اكتب الحروف من خلال الصورة<br />',//'输入下图中的字符<br />',
	'seccode_image_ani_tips'	=> 'اكتب الاحرف من الصورة<br />',//'输入下面动画图片中最大的字符<br />',
	'seccode_sound_tips'		=> 'اكتب الاحرف التي تسمعها<br />',//'输入你听到的字符<br />',
	'secqaa_tips'			=> 'أدخل الاجابة للسؤال التالي<br />',//'输入下面问题的答案<br />',

	'fullblankspace'		=> '&nbsp;',//'　',

	'title_goruptype'		=> 'نوع المجموعة',//'类',
	'title_of'			=> ' من ',//'的',
	'title_board_message'		=> 'رسالة',//'提示信息',
	'title_view_all'		=> 'عرض الكل',//'随便看看',
	'title_activity'		=> 'الفعاليات',//'活动',
	'title_friend_activity'		=> 'فعاليات الاصدقاء',//'好友发起的活动',
	'title_my_activity'		=> 'فعالياتي',//'我的活动',
	'title_newest_activity'		=> 'الفعاليات الجديدة',//'最新活动',
	'title_top_activity'		=> 'اعلى الفعاليات',//'热门活动',
	'title_album'			=> 'الالبومات',//'相册',
	'title_friend_album'		=> 'البومات الاصدقاء',//'好友的相册',
	'title_my_album'		=> 'ألبوماتي',//'我的相册',
	'title_newest_update_album'	=> 'اخر الالبومات المحدثة',//'最新更新的相册',
	'title_hot_pic_recommend'	=> 'افضل الصور',//'热门图片推荐',
	'title_blog'			=> 'المدونات',//'日志',
	'title_friend_blog'		=> 'مدونات الاصدقاء',//'好友的日志',
	'title_my_blog'			=> 'مدوناتي',//'我的日志',
	'title_post_new_blog'		=> 'اضافة مدونة جديدة',//'发表新日志',
	'title_newest_blog'		=> 'المدونات الجديدة',//'最新发表的日志',
	'title_recommend_blog'		=> 'المدونات المستحسنة',//'推荐阅读的日志',
	'title_debate'			=> 'المناقشات',//'辩论',
	'title_friend_debate'		=> 'مناقشات الاصدقاء',//'好友发起的辩论',
	'title_my_debate'		=> 'تحدياتي',//'我的辩论',
	'title_create_new_debate'	=> 'كتاية تحديات',//'发起新辩论',
	'title_my_create_debate'	=> 'تحديات انشاءت بواسطتي',//'我发起的辩论',
	'title_my_join_debate'		=> 'مشترك بها',//'我参与的辩论',
	'title_newest_debate'		=> 'التحديات الجديدة',//'最新辩论',
	'title_top_debate'		=> 'افضل التحديات',//'热门辩论',
	'title_doing'			=> 'الافعال',//'记录',
	'title_newest_doing'		=> 'الافعال الجديدة',//'记录',
	'title_me_friend_doing'		=> 'أفعال الاصدقاء',//'我和好友的记录',
	'title_doing_view_me'		=> 'أفعالي',//'我的记录',
	'title_thread_favorite'		=> 'المواضيع المفضلة',//'帖子收藏',
	'title_forum_favorite'		=> 'الاقسام المفضلة',//'帖子收藏',
	'title_group_favorite'		=> 'المجموعات المفضلة &quot;{gorup}&quot;',//'{gorup} 收藏',
	'title_blog_favorite'		=> 'المدونات المفضلة',//'日志收藏',
	'title_album_favorite'		=> 'الالبومات المفضلة',//'相册收藏',
	'title_article_favorite'	=> 'المقالات المفضلة',//'文章收藏',
	'title_all_favorite'		=> 'المفضلة',//'全部收藏',
	'title_friend_list'		=> 'قائمة الاصدقاء',//'好友列表',
	'title_of'			=> ' من ',//'的',
	'title_all_poll'		=> 'جميع الاستطلاعات',//'随便看看投票',
	'title_we_poll'			=> 'استطلاعات الاصدقاء',//'好友发起的投票',
	'title_me_poll'			=> 'استطلاعاتي',//'我的投票',
	'title_hot_poll'		=> 'الاستطلاعات النشطة',//'热门投票',
	'title_dateline_poll'		=> 'اخر الاستطلاعات',//'最新投票',
	'title_all_reward'		=> 'كل الطلبات',//'随便看看悬赏',
	'title_we_reward'		=> 'طلبات الاصدقاء',//'好友发起的悬赏',
	'title_me_reward'		=> 'طلباتي',//'我的悬赏',
	'title_hot_reward'		=> 'الطلبات النشطة',//'热门悬赏',
	'title_dateline_reward'		=> 'اخر الطلبات',//'最新悬赏',
	'title_share_all'		=> 'الكل',//'全部',
	'title_share_link'		=> 'روابط',//'网址',
	'title_share_video'		=> 'فيديو',//'视频',
	'title_share_music'		=> 'موسيقى',//'音乐',
	'title_share_flash'		=> 'فلاش',
	'title_share_poll'		=> 'استطلاعات',//'投票',
	'title_share_pic'		=> 'صور',//'图片',
	'title_share_album'		=> 'البومات',//'相册',
	'title_share_blog'		=> 'مدونات',//'日志',
	'title_share_space'		=> 'اعضاء',//'用户',
	'title_share_thread'		=> 'مواضيع',//'帖子',
	'title_share_article'		=> 'مقالات',//'文章',
	'title_share_tag'		=> 'كلمات دلالية',//'TAG',
	'title_share'			=> 'منشورات',//'分享',
	'title_thread'			=> 'مواضيع',//'帖子',
	'title_all_thread'		=> 'كل المواضيع',//'随便看看帖子',
	'title_we_thread'		=> 'مواضيع الاصدقاء',//'好友发起的帖子',
	'title_me_thread'		=> 'مواضيعي',//'我的帖子',
	'title_hot_thread'		=> 'المواضيع النشيطة',//'热门帖子',
	'title_dateline_thread'		=> 'اخر المواضيع',//'最新帖子',
	'title_trade'			=> 'المنتجات',//'商品',
	'title_all_trade'		=> 'كل المنتجات',//'随便看看商品',
	'title_we_trade'		=> 'منتجات الاصدقاء',//'好友出售的商品',
	'title_me_trade'		=> 'منتجاتي',//'我的商品',
	'title_hot_trade'		=> 'المنتجات النشطة',//'热门商品',
	'title_dateline_trade'		=> 'اخر المنتجات',//'最新商品',
	'title_tradelog_trade'		=> 'معاملات المنتجات',//'交易记录',
	'title_eccredit_trade'		=> 'عمليات النقاط',//'信用评价',
	'title_credit'			=> 'النقاط',//'积分',
	'title_friend_add'		=> 'اضافة اصدقاء',//'添加好友',
	'title_people_might_know'	=> 'قد يكون من المعروف',//'可能认识的人',
	'title_friend_request'		=> 'طلب صديق',//'好友请求',
	'title_search_friend'		=> 'بحث عن اصدقاء',//'查找好友',
	'title_invite_friend'		=> 'دعوة اصدقاء',//'邀请好友',
	'title_password_security'	=> 'امان كلمة المرور',//'密码安全',
	'title_flash_upload'		=> 'الرفع',//'批量上传',
	'title_cam_upload'		=> 'رفع من الكاميرا',//'大头贴',
	'title_normal_upload'		=> 'الرفع العام',//'普通上传',
	'title_newthread_post'		=> 'اضافة موضوع جديد',//'发表帖子',
	'title_reply_post'		=> 'رد على الموضوع',//'参与/回复主题',
	'title_edit_post'		=> 'تعديل المشاركة',//'编辑帖子',
	'title_newtrade_post'		=> 'اضافة منتج',//'发布商品',
	'title_magics_shop'		=> 'متجر الدعائم',//'道具商店',
	'title_magics_hot'		=> 'الدعائم الاكثر شعبية',//'热销道具',
	'title_magics_user'		=> 'دعائمي',//'我的道具',
	'title_magics_log'		=> 'سجل الدعائم',//'道具记录',
	'title_medals_list'		=> 'قائمة الاوسمة',//'勋章',
	'title_setup'			=> 'الاعدادات',//'设置',
	'title_memcp_blog'		=> 'نشر مدونة',//'发表日志',
	'title_memcp_upload'		=> 'رفع',//'上传',
	'title_memcp_share'		=> 'اضافة منشور',//'添加分享',
	'title_memcp_sendmail'		=> 'تنبيهات البريد',//'邮件提醒',
	'title_memcp_privacy'		=> 'الخصوصية',//'隐私筛选',
	'title_memcp_avatar'		=> 'تعديل الصورة الرمزية',//'修改头像',
	'title_memcp_profile'		=> 'البيانات الشخصية',//'个人资料',
	'title_memcp_sendmail'		=> 'تنبيه البريد',//'邮件提醒',
	'title_memcp_credit'		=> 'النقاط',//'积分',
	'title_memcp_friend'		=> 'الاصدقاء',//'好友',
	'title_memcp_usergroup'		=> 'مجموعات العضو',//'用户组',
	'title_memcp_album'		=> 'الالبومات',//'编辑相册',
	'title_memcp_poke'		=> 'رسائل التحية',//'打招呼',
	'title_memcp_videophoto'	=> 'تحقق الفيديو',//'视频认证',
	'title_memcp_comment'		=> 'تعليقات',//'评论',
	'title_memcp_eccredit'		=> 'عمليات النقاط',//'信用评价',
	'title_memcp_promotion'	=> 'تشجيع الوصول',
	'title_task'			=> 'المهام',//'任务',
	'title_login'			=> 'تسجيل الدخول',//'登录',
	'title_ranklist_picture'	=> 'رتب الصورة',//'图片排行',
	'title_ranklist_member'		=> 'رتب الاعضاء',//'用户排行',
	'title_ranklist_thread'		=> 'رتب المواضيع',//'帖子排行',
	'title_ranklist_blog'		=> 'رتب المدونات',//'日志排行',
	'title_ranklist_poll'		=> 'رتب الاستطلاعات',//'投票排行',
	'title_ranklist_activity'	=> 'رتب الفعاليات',//'活动排行',
	'title_ranklist_forum'		=> 'رتب الاقسام',//'版块排行',
	'title_ranklist_group'		=> 'رتب المجموعات',//'群组排行',
	'title_ranklist_app'	=> 'ترتيب التطبيقات',//'应用排行',
	'title_ranklist_index'		=> 'رتب الكل',//'全部排行',
//	'title_ranklist_index'		=> 'Rank',//'排行榜',
	'title_search'			=> 'بحث',//'搜索',
	'title_topic_management'	=> 'ادارة المواضيع',//'创建专题',
	'title_portal_management'	=> 'ادارة المجلة',//'门户管理',
	'title_portalblock_management'	=> 'ادارة مربعات المجلة',//'模块管理',
	'title_block_management'	=> 'ادارة الكتل',//'模块管理',
	'title_blockdata_management'	=> 'ادارة بيانات الكتل',//'推送审核',
	'title_index_management'	=> 'ادارة القنوات',//'频道栏目',
	'title_article_management'	=> 'ادارة المقالات',//'发布文章',
	'title_category_management'	=> 'ادارة الاقسام',//'管理文章',

	'title_stats'			=> 'احصائيات المنتدى',//'站点统计',
	'title_stats_basic'		=> 'الاحصائيات العامة',//'基本概况',
	'title_stats_forumstat'		=> 'احصائيات الاقسام',//'版块统计',
	'title_stats_team'		=> 'احصائيات الفريق',//'管理团队',
	'title_stats_modworks'		=> 'احصائيات المشرفين',//'管理统计',
	'title_stats_memberlist'	=> 'قائمة الاعضاء',//'会员列表',
	'title_stats_trend'		=> 'احصائيات المعاملات',//'趋势统计',

	'title_memcp_pm'		=> 'إرسال رسالة',//'发送短消息',
	'title_memcp_domain'		=> 'نطاق ملفي الشخصي',//'我的空间域名',
	'title_userapp'			=> 'التطبيقات',//'应用',
	'title_userapp_index_all'	=> 'جميع التطبيقات',//'大家在玩什么',
	'title_userapp_index_we'	=> 'تطبيقات الاصدقاء',//'好友在玩什么',
	'title_userapp_index_me'	=> 'تطبيقاتي',//'我在玩的',
	'title_userapp_manage'		=> 'ادارة التطبيقات &quot;{userapp}&quot;',//'{userapp}管理',
	'faq'	=> 'التعليمات',//'帮助',
	'search'	=> 'بحث',//'搜索',

//vot source/include/misc/misc_security.php
	'attackevasive_1_subject'	=> 'Refresh frequency limit',
	'attackevasive_1_message'	=> 'You visit the site too fast, less than two seconds! Please wait a little...',
	'attackevasive_2_subject'	=> 'Access throug proxy servers is restricted',
	'attackevasive_2_message'	=> 'Access to the site through a proxy servers is restricted for mow. Please remove your proxy setting configuration, and access to the site directly.',
	'attackevasive_4_subject'	=> 'Open the page reload',
	'attackevasive_4_message'	=> 'Welcome to the site, the page is re-loading, please wait ...',

//vot Months Names
	'month_name'	=> array('Month','January','February','March','April','May','June','July','August','September','October','November','December'),

);

?>