<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_activitylist.php by Valery Votintsev at sources.ru
 */

$lang = array
(
	'activitylist_fids'			=> 'Форум',
	'activitylist_fids_comment'		=> 'Вы можете выбрать несколько значений, удерживая клавишу CTRL. Если ничего не выбрано - без ограничений',
	'activitylist_uids'			=> 'UID пользователя',
	'activitylist_uids_comment'		=> 'Для нескольких значений, используйте запятую с пробелом',
	'activitylist_startrow'			=> 'Первоначальное количество строк',
	'activitylist_startrow_comment'		=> 'Чтобы задать начальное количество строк, введите значения. Например: 0, чтобы начать с первой линии и так далее...',
	'activitylist_items'			=> 'Отображение количества записей в статьях',
	'activitylist_items_comment'		=> 'Отображение количества записей в статьях. Установите целое число, больше 0',
	'activitylist_titlelength'		=> 'Максимальное количество байт в названии',
	'activitylist_titlelength_comment'	=> 'Настройка длинны символов заголовка. Если заголовок больше указанного значения, длинна названия будет автоматически урезана до указанного значения. Если - 0, не урезать',
	'activitylist_fnamelength'		=> 'Название форума содержит максимальное количество байт',
	'activitylist_fnamelength_comment'	=> 'Укажите необходимые значения',
	'activitylist_summarylength'		=> 'Анонс (краткое содержание) темы',
	'activitylist_summarylength_comment'	=> 'Установить значение для текста, используйте значение по умолчанию от 0 до 255',
	'activitylist_tids'			=> 'Указание тем',
	'activitylist_tids_comment'		=> 'Укажите tid тем, если несколько tid укажите их через запятую. Оставьте пустым, чтобы использовать без фильтра',
	'activitylist_keyword'			=> 'Ключевое слово заглавия',
	'activitylist_keyword_comment'		=> 'Задать ключевые слова для заголовка. Оставьте пустым, чтобы использовать без фильтра. В ключевых слова можно использовать символ: *',
	'activitylist_typeids'			=> 'Категории тем',
	'activitylist_typeids_comment'		=> 'Установите категории для тем. Оставьте пустым, чтобы использовать без фильтра',
	'activitylist_typeids_all'		=> 'Все категории тем',
	'activitylist_sortids'			=> 'Информация о категории',
	'activitylist_sortids_comment'		=> 'Установить тему секретной информации. Оставьте пустым, чтобы использовать без фильтра',
	'activitylist_sortids_all'		=> 'Все',
	'activitylist_digest'			=> 'Дайджест тем',
	'activitylist_digest_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'activitylist_digest_0'			=> 'Общие темы',
	'activitylist_digest_1'			=> 'Дайджест I',
	'activitylist_digest_2'			=> 'Дайджест II',
	'activitylist_digest_3'			=> 'Дайджест III',
	'activitylist_stick'			=> 'Важная тема',
	'activitylist_stick_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'activitylist_stick_0'			=> 'Общие темы',
	'activitylist_stick_1'			=> 'Топ I',
	'activitylist_stick_2'			=> 'Топ II',
	'activitylist_stick_3'			=> 'Топ III',
	'activitylist_special'			=> 'Специальные темы',
	'activitylist_special_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'activitylist_special_1'		=> 'Темы опросов',
	'activitylist_special_2'		=> 'Темы товаров',
	'activitylist_special_3'		=> 'Темы платные',
	'activitylist_special_4'		=> 'Темы событий',
	'activitylist_special_5'		=> 'Темы поединков',
	'activitylist_special_0'		=> 'Все темы',
	'activitylist_special_reward'		=> 'Фильтр тем наград',
	'activitylist_special_reward_comment'	=> 'Установить для темы определенный тип награды',
	'activitylist_special_reward_0'		=> 'Все',
	'activitylist_special_reward_1'		=> 'Выданные',
	'activitylist_special_reward_2'		=> 'Не выданные',
	'activitylist_recommend'		=> 'Фильтр рекомендуемых тем',
	'activitylist_recommend_comment'	=> 'Укажите параметры рекомендуемых тем',
	'activitylist_orderby'			=> 'Сортировка тем',
	'activitylist_orderby_comment'		=> 'Настройка фильтра сортировки',
	'activitylist_orderby_lastpost'		=> 'По дате создания',
	'activitylist_orderby_dateline'		=> 'По дате сроку действия',
	'activitylist_orderby_replies'		=> 'По числу ответов',
	'activitylist_orderby_views'		=> 'По просмотрам',
	'activitylist_orderby_heats'		=> 'По популярности',
	'activitylist_orderby_recommends'	=> 'По рекомендациям',
	'activitylist_orderby_hourviews'	=> 'По просмотрам в течении часа',
	'activitylist_orderby_todayviews'	=> 'По просмотрам в течении дня',
	'activitylist_orderby_weekviews'	=> 'По просмотрам в течении недели',
	'activitylist_orderby_monthviews'	=> 'По просмотрам в течении месяца',
	'activitylist_orderby_hours'		=> 'По заданному времени (по часам)',
	'activitylist_orderby_hours_comment'	=> 'Просмотр в течение указанного времени',
	'activitylist_orderby_todayhots'	=> 'Общее количество продаж за сегодня',
	'activitylist_orderby_weekhots'		=> 'Общее количество продаж за неделю',
	'activitylist_orderby_monthhots'	=> 'Общее количество продаж за месяц',
	'activitylist_price_add'		=> 'Дополнительно',
	'activitylist_place'			=> 'Место события',
	'activitylist_class'			=> 'Тип события',
	'activitylist_class_all'		=> 'Все типы',
	'activitylist_gender'			=> 'Пол',
	'activitylist_gender_0'			=> 'Неизвестно',
	'activitylist_gender_1'			=> 'муж',
	'activitylist_gender_2'			=> 'жен',
	'activitylist_orderby_weekstart'	=> 'Начало события за неделю',
	'activitylist_orderby_monthstart'	=> 'Начало события за месяц',
	'activitylist_orderby_weekexp'		=> 'Окончание приема заявок за неделю',
	'activitylist_orderby_monthexp'		=> 'Окончание приема заявок за месяц',
	'activitylist_orderby_weekhot'		=> 'По популярности за неделю',
	'activitylist_orderby_monthhot'		=> 'По популярности за месяц',
	'activitylist_orderby_alltimehot'	=> 'Закончившиеся события',
	'activitylist_highlight'		=> 'Выделение полученных значений',
);

?>