<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_tradelist.php by Valery Votintsev at sources.ru
 */

$lang = array
(
	'tradelist_fids'		=> 'Форум',
	'tradelist_fids_comment'	=> 'Вы можете выбрать несколько значений, удерживая клавишу CTRL. Если ничего не выбрано - без ограничений',
	'tradelist_uids'		=> 'UID пользователя',
	'tradelist_uids_comment'	=> 'Для нескольких значений, используйте запятую с пробелом',
	'tradelist_startrow'		=> 'Первоначальное количество строк',
	'tradelist_startrow_comment'	=> 'Чтобы задать начальное количество строк, введите значения. Например: 0, чтобы начать с первой линии и так далее...',
	'tradelist_items'		=> 'Отображение количества записей в статьях',
	'tradelist_items_comment'	=> 'Отображение количества записей в статьях. Установите целое число, больше 0',
	'tradelist_titlelength'		=> 'Максимальное количество байт в названии',
	'tradelist_titlelength_comment'	=> 'Настройка длинны символов заголовка. Если заголовок больше указанного значения, длинна названия будет автоматически урезана до указанного значения. Если - 0, не урезать',
	'tradelist_fnamelength'		=> 'Название форума содержит максимальное количество байт',
	'tradelist_fnamelength_comment'	=> 'Укажите необходимые значения',
	'tradelist_summarylength'	=> 'Анонс (краткое содержание) темы',
	'tradelist_summarylength_comment'	=> 'Установить значение для текста, используйте значение по умолчанию от 0 до 255',
	'tradelist_tids'		=> 'Указание тем',
	'tradelist_tids_comment'	=> 'Укажите tid тем, если несколько tid укажите их через запятую. Оставьте пустым, чтобы использовать без фильтра',
	'tradelist_keyword'		=> 'Ключевое слово заглавия',
	'tradelist_keyword_comment'	=> 'Задать ключевые слова для заголовка. Оставьте пустым, чтобы использовать без фильтра. В ключевых слова можно использовать символ: *',
	'tradelist_typeids'		=> 'Категории тем',
	'tradelist_typeids_comment'	=> 'Установите категории для тем. Оставьте пустым, чтобы использовать без фильтра',
	'tradelist_typeids_all'		=> 'Все категории тем',
	'tradelist_sortids'		=> 'Информация о категории',
	'tradelist_sortids_comment'	=> 'Установить тему секретной информации. Оставьте пустым, чтобы использовать без фильтра',
	'tradelist_sortids_all'		=> 'Все',
	'tradelist_digest'		=> 'Дайджест тем',
	'tradelist_digest_comment'	=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'tradelist_digest_0'		=> 'Общие темы',
	'tradelist_digest_1'		=> 'Дайджест I',
	'tradelist_digest_2'		=> 'Дайджест II',
	'tradelist_digest_3'		=> 'Дайджест III',
	'tradelist_stick'		=> 'Важная тема',
	'tradelist_stick_comment'	=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'tradelist_stick_0'		=> 'Общие темы',
	'tradelist_stick_1'		=> 'Топ I',
	'tradelist_stick_2'		=> 'Топ II',
	'tradelist_stick_3'		=> 'Топ III',
	'tradelist_special'		=> 'Специальные темы',
	'tradelist_special_comment'	=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'tradelist_special_1'		=> 'Темы опросов',
	'tradelist_special_2'		=> 'Темы товаров',
	'tradelist_special_3'		=> 'Темы платные',
	'tradelist_special_4'		=> 'Темы событий',
	'tradelist_special_5'		=> 'Темы поединков',
	'tradelist_special_0'		=> 'Все темы',
	'tradelist_special_reward'	=> 'Фильтр тем наград',
	'tradelist_special_reward_comment'	=> 'Установить для темы определенный тип награды',
	'tradelist_special_reward_0'	=> 'Все',
	'tradelist_special_reward_1'	=> 'Выданные',
	'tradelist_special_reward_2'	=> 'Не выданные',
	'tradelist_recommend'		=> 'Фильтр рекомендуемых тем',
	'tradelist_recommend_comment'	=> 'Укажите параметры рекомендуемых тем',
	'tradelist_orderby'		=> 'Сортировка тем',
	'tradelist_orderby_comment'	=> 'Настройка фильтра сортировки',
	'tradelist_orderby_lastpost'	=> 'По дате создания',
	'tradelist_orderby_dateline'	=> 'По дате сроку действия',
	'tradelist_orderby_replies'	=> 'По числу ответов',
	'tradelist_orderby_views'	=> 'По просмотрам',
	'tradelist_orderby_heats'	=> 'По популярности',
	'tradelist_orderby_recommends'	=> 'По рекомендациям',
	'tradelist_orderby_hourviews'	=> 'По просмотрам в течении часа',
	'tradelist_orderby_todayviews'	=> 'По просмотрам в течении дня',
	'tradelist_orderby_weekviews'	=> 'По просмотрам в течении недели',
	'tradelist_orderby_monthviews'	=> 'По просмотрам в течении месяца',
	'tradelist_orderby_hours'		=> 'По заданному времени (по часам)',
	'tradelist_orderby_hours_comment'	=> 'Просмотр в течение указанного времени',
	'tradelist_orderby_todayhots'	=> 'Общее количество продаж за сегодня',
	'tradelist_orderby_weekhots'	=> 'Общее количество продаж за неделю',
	'tradelist_orderby_monthhots'	=> 'Общее количество продаж за месяц',
	'tradelist_price_add'		=> 'Дополнительно',
	'tradelist_place'		=> 'Место события',
	'tradelist_class'		=> 'Тип события',
	'tradelist_gender'		=> 'Пол',
	'tradelist_gender_0'		=> 'Неизвестно',
	'tradelist_gender_1'		=> 'муж',
	'tradelist_gender_2'		=> 'жен',
	'tradelist_orderby_weekstart'	=> 'Начало события за неделю',
	'tradelist_orderby_monthstart'	=> 'Начало события за месяц',
	'tradelist_orderby_weekexp'	=> 'Окончание приема заявок за неделю',
	'tradelist_orderby_monthexp'	=> 'Окончание приема заявок за месяц',
	'tradelist_highlight'		=> 'Выделить значение', 
);

