<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_groupthread.php by Valery Votintsev at sources.ru
 */

$lang = array
(
	'groupthread_fids'			=> 'ID группы',
	'groupthread_fids_comment'		=> 'Укажите ID через запятую',
	'groupthread_gtids'			=> 'Категория гуппы'
	'groupthread_gtids_comment'		=> 'Вы можете выбрать несколько значений, удерживая клавишу CTRL. Если ничего не выбрано - без ограничений',
	'groupthread_uids'			=> 'UID пользователя',
	'groupthread_uids_comment'		=> 'Для нескольких значений, используйте запятую с пробелом',
	'groupthread_keyword'			=> 'Ключевое слово заглавия',
	'groupthread_keyword_comment'		=> 'Задать ключевые слова для заголовка. Оставьте пустым, чтобы использовать без фильтра. В ключевых слова можно использовать символ: *',
	'groupthread_startrow'			=> 'Первоначальное количество строк',
	'groupthread_startrow_comment'		=> 'Чтобы задать начальное количество строк, введите значения. Например: 0, чтобы начать с первой линии и так далее...',
	'groupthread_items'			=> 'Отображение количества записей в статьях',
	'groupthread_items_comment'		=> 'Отображение количества записей в статьях. Установите целое число, больше 0',
	'groupthread_titlelength'		=> 'Максимальное количество байт в названии',
	'groupthread_maxlength_comment'		=> 'Если титул больше, чем установленого значения, тогда название автоматически уменьшается на указанное количество байт, если 0 - не будет автоматически уменьшаться',
	'groupthread_fnamelength'		=> 'Название форума содержит максимальное количество байт',
	'groupthread_fnamelength_comment'	=> 'Укажите необходимые значения',
	'groupthread_summarylength'		=> 'Анонс (краткое содержание) темы',
	'groupthread_summarylength_comment'	=> 'Установить значение для текста, используйте значение по умолчанию от 0 до 255',
	'groupthread_picpre'			=> 'Иконка префикса',
	'groupthread_picpre_comment'		=> 'Иконка добавляется впереди, в виде иконки. Введите URL изображения (абсолютное или относительное) адрес может быть',
	'groupthread_tids'			=> 'Указание тем',
	'groupthread_tids_comment'		=> 'Укажите tid тем, если несколько tid укажите их через запятую. Оставьте пустым, чтобы использовать без фильтра',
//	'groupthread_keyword'			=> 'Keywords',//'标题关键字',
//	'groupthread_keyword_comment'		=> 'Set the keywords used.<br />You can use wildcard "*" in keywords.<br />If you want to use some keywords at same time, you can use "AND". Example: win32 AND unix.<br />If you want to use just one of keywords, you can use "|" or "OR". Example: win32 OR unix',//'设置标题包含的关键字。注意: 留空为不进行任何过滤<br />关键字中可使用通配符 "*"<br />匹配多个关键字全部，可用空格或 "AND" 连接。如 win32 AND unix<br />匹配多个关键字其中部分，可用 "|" 或 "OR" 连接。如 win32 OR unix',
	'groupthread_typeids'			=> 'Категории тем',
	'groupthread_typeids_comment'		=> 'Установите категории для тем. Оставьте пустым, чтобы использовать без фильтра',
	'groupthread_typeids_all'		=> 'Все категории тем',
	'groupthread_sortids'			=> 'Информация о категории',
	'groupthread_sortids_comment'		=> 'Установить тему секретной информации. Оставьте пустым, чтобы использовать без фильтра',
	'groupthread_sortids_all'		=> 'Все',
	'groupthread_threadtype'		=> 'Показ префикса в темах категорий',
	'groupthread_threadtype_comment'	=> 'Установка префикса в темах категорий',
	'groupthread_groupthreadort'		=> 'Показ номеров в категориях информаций',
	'groupthread_groupthreadort_comment'	=> 'Установка номерного списка в теме информации',
	'groupthread_highlight'			=> 'Подсветка тем',
	'groupthread_highlight_comment'		=> 'Указать, следует ли отображать подстветку тем',
	'groupthread_digest'			=> 'Дайджест тем',
	'groupthread_digest_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'groupthread_digest_0'			=> 'Общие темы',
	'groupthread_digest_1'			=> 'Дайджест I',
	'groupthread_digest_2'			=> 'Дайджест II',
	'groupthread_digest_3'			=> 'Дайджест III',
	'groupthread_stick'			=> 'Важная тема',
	'groupthread_stick_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'groupthread_stick_0'			=> 'Общие темы',
	'groupthread_stick_1'			=> 'Топ I',
	'groupthread_stick_2'			=> 'Топ II',
	'groupthread_stick_3'			=> 'Топ III',
	'groupthread_special'			=> 'Специальные темы',
	'groupthread_special_comment'		=> 'Установите конкретную предметную область. Примечание: Оставьте пустым, чтобы использовать без фильтра',
	'groupthread_special_1'			=> 'Темы опросов',
	'groupthread_special_2'			=> 'Темы товаров',
	'groupthread_special_3'			=> 'Темы платные',
	'groupthread_special_4'			=> 'Темы событий',
	'groupthread_special_5'			=> 'Темы поединков',
	'groupthread_special_0'			=> 'Все темы',
	'groupthread_special_reward'		=> 'Фильтр тем наград',
	'groupthread_special_reward_comment'	=> 'Установить для темы определенный тип награды',
	'groupthread_picrequired'		=> 'Установка вложений изображений',
	'groupthread_picrequired_comment'	=> 'Установка вложений изображений',
	'groupthread_special_reward_0'		=> 'Все',
	'groupthread_special_reward_1'		=> 'Выданные',
	'groupthread_special_reward_2'		=> 'Не выданные',
	'groupthread_recommend'			=> 'Фильтр рекомендуемых тем',
	'groupthread_recommend_comment'		=> 'Укажите параметры рекомендуемых тем',
	'groupthread_orderby'			=> 'Сортировка тем',
	'groupthread_orderby_comment'		=> 'Настройка фильтра сортировки',
	'groupthread_orderby_lastpost'		=> 'По дате создания',
	'groupthread_orderby_dateline'		=> 'По дате сроку действия',
	'groupthread_orderby_replies'		=> 'По числу ответов',
	'groupthread_orderby_views'		=> 'По просмотрам',
	'groupthread_orderby_heats'		=> 'По популярности',
	'groupthread_orderby_recommends'	=> 'По рекомендациям',
	'groupthread_orderby_hourviews'		=> 'По просмотрам в течении часа',
	'groupthread_orderby_todayviews'	=> 'По просмотрам в течении дня',
	'groupthread_orderby_weekviews'		=> 'По просмотрам в течении недели',
	'groupthread_orderby_monthviews'	=> 'По просмотрам в течении месяца',
	'groupthread_postdateline'		=> 'Опубликованные темы',
	'groupthread_postdateline_nolimit'	=> 'Без лимита',
	'groupthread_postdateline_hour'		=> '1 час',
	'groupthread_postdateline_day'		=> 'Сутки',
	'groupthread_postdateline_week'		=> 'Неделя', 
	'groupthread_postdateline_month'	=> '1 мес.',
	'groupthread_lastpost'			=> 'Последнее обновление',
	'groupthread_lastpost_nolimit'		=> 'Без ограничений',
	'groupthread_lastpost_hour'		=> 'За час',
	'groupthread_lastpost_day'		=> 'За сутки',
	'groupthread_lastpost_week'		=> 'За неделю',
	'groupthread_lastpost_month'		=> 'За месяц',
	'groupthread_orderby_displayorder'	=> 'Порядок по умолчанию',
	'groupthread_gviewperm'			=> 'Обзор разрешений групп',
	'groupthread_gviewperm_nolimit'		=> 'Без ограничений',
	'groupthread_gviewperm_only_member'	=> 'Только для членов',
	'groupthread_gviewperm_all_member'	=> 'Все',
	'groupthread_highlight'			=> 'Highlight found words',
);

