<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_template.php by Valery Votintsev at sources.ru
 *
 *      This file is automatically generate
 */

$lang = array (
	'activity_about_member'		=> 'Remaining places',//'剩余名额',
	'activity_already'		=> 'Katılım',
	'additional'			=> 'Additional',
	'debate_opponent'		=> 'Karşı',
	'debate_square'			=> 'Taraf',
	'thread_poll'			=> 'Anketler',
	'credits'			=> 'Puan',
	'login'				=> 'Giriş',
	'active_email'			=> 'Receive E-mail',//'接收邮箱',
	'active_email_comment'		=> 'Required to receive an invitation code to E-mail Address',//'必填，用来接收邀请码的邮箱地址',
	'apitype_alipay'		=> 'Alipay',
	'apitype_tenpay'		=> 'Tenpay',
	'buy_nums'			=> 'Quantity',
	'confirms'			=> 'Onayla',
	'copycode'			=> 'Copy all to clipboard',//'全部复制到剪贴板',
	'copycode_invite_succeed'	=> 'Invitation code has been copied to the clipboard',//'邀请码已经复制到剪贴板',
	'invitecode_buycode'		=> 'Obtain invitation code',//'获取邀请码',
	'invitecode_email'		=> 'We will also sent invite code to your mailbox <span class="xi1">$order[email]</span> for inspection',//'我们还将邀请码发送到了您填写的邮箱 <span class="xi1">$order[email]</span> 以备查阅',
	'invitecode_expiration'		=> 'Expiration time',//'失效时间',
	'invitecode_succeed_title'	=> 'Congratulations, you have successfully obtained invite code',//'恭喜您，成功获得邀请码',
	'money_unit'			=> 'USD',//'元',
	'need_money'			=> 'Required to pay',//'需支付',
	'reg_continue'			=> 'Continue Registration',//'继续注册',
	'trade_type'			=> 'Payment method',//'付款方式',
	'e_fontoptions'			=> '"Arial", "Verdana", "Tahoma", "Times New Roman", "Impact", "Trebuchet MS"',//'"仿宋_GB2312", "黑体", "楷体_GB2312", "宋体", "新宋体", "微软雅黑", "Trebuchet MS", "Tahoma", "Arial", "Impact", "Verdana", "Times New Roman"',
	'editor_increase'	=> 'Geni_let',
	'editor_narrow'		=> 'Daralt',
	'post_autosave_restore'	=> 'Data recovery',
	'post_check_length'	=> 'Kelime kontrol',
	'post_savedata'		=> 'Kaydet',
	'post_topicreset'	=> 'Temizle',
	'all'				=> 'All',//'全部',
	'faq'			=> 'SSS',
	'faq_search_nomatch'	=> '_zg_n_z, hiçbir sonuç bulunamad+',
	'homepage'		=> 'Anasayfa',
	'keyword_faq'		=> 'Keywords"<span class="xi1">$keyword</span>"Help',
	'open'			=> 'Aç',
	'search'		=> 'Arama',
	'close'			=> 'Kapa',
	'focus_hottopics'	=> '-nerilenler',
	'focus_show'		=> 'Göster',
	'login_invisible_mode'	=> 'Gör_nmez',
	'login_normal_mode'	=> 'Online',
	'scrolltop'			=> 'To Top',//'回顶部',
	'thread_groupupgrade'	=> '_st grup için gereken:',
	'time_now'		=> 'T_m zamanlar GMT{$_G[timenow][offset]}, {$_G[timenow][time]}',
	'activation'		=> 'Etkinle_tir',
	'admincp'		=> 'Manage Site',
	'changestyle'			=> 'Change Style',//'切换风格',
	'default'			=> 'Default',//'默认',
	'forum_manager'		=> 'D_zenle Forum',
	'go_to_mobile'			=> 'To the mobile version',//'进入手机版',
	'login_switch_invisible_mode'	=> 'De_i_tir',
	'logout'		=> '++k+_',
	'my_nav'		=> 'Men_',
	'my_nav_login'		=> 'L_tfen <a href="javascript:;" class="xi2" onclick="lsSubmit()"><strong>giri_ yap+n+z </strong></a> veya <br /> <a href="member.php?mod={$_G[setting][regname]}" class="xi2 xw1">Register olunuz</a>',
	'open_diy'		=> 'DIY Panel',
	'pm_center'		=> '-.M',
	'portal_block_manage'		=> 'Block Management',//'模块管理',
	'portal_manage'		=> 'Portal CP',
	'remind'		=> 'Hat+rlatma',
	'setup'			=> 'Ayarlar',
	'switch_narrow'		=> 'Dar',
	'switch_wide'		=> 'Geni_',
	'task_doing'		=> 'Geçerli',
	'to_be_continue'		=> 'Continue to access the desktop computer version',//'Ԧ',
	'usergroup'	=> '_yegrup',
	'visit_my_space'		=> 'Visit My Space',//'+',
	'your_mobile_browser'		=> 'Please select ',//' ',
	'e_redo'	=> 'Tekrar',
	'e_undo'	=> 'Geri',
	'header_add_frame'	=> '+erçeve ekle',
	'header_add_module'	=> 'Mod_l ekle',
	'header_clearall'	=> 'Temizle',
	'header_clearall_desc'	=> 'Clear all DIY data of current page',
	'header_diy'	=> '-zel',
	'header_diy_backup_tip'	=> 'Yard+m',
	'header_diy_i_know'	=> 'Gereksiz',
	'header_diy_sample_mode'	=> 'Simple<strong> model</strong>, You can update and modify the modules in <a href="javascript:;" onclick="spaceDiy.init();" class="xw1 xi2">Advanced</a>',
	'header_export'	=> 'D+_a al',
	'header_export_desc'	=> 'Export all DIY data of current page',
	'header_frame'	=> '+erçeve',
	'header_import'	=> 'Import',
	'header_import_desc'	=> 'Import DIY data to current page',
	'header_module'	=> 'Mod_l',
	'header_more_actions'	=> 'More',
	'header_perview'	=> '-nizleme',
	'header_perview_desc'	=> '-nizleme DIY',
	'header_restore_backup'	=> 'Geri al',
	'header_restore_backup_desc'	=> 'Geri al',
	'header_start'	=> 'Start',
	'header_update'	=> 'G_ncelle',
	'header_update_desc'	=> 'Update all datas of current page modules',
	'save'	=> 'Kaydet',
	'style'	=> 'Stil',
	'find'	=> 'Arama ',
	'invite'	=> 'Davet',
	'invite_all_friend'	=> 'T_m arkada_lar',
	'invite_friend'	=> 'Arkada_ davetle ',
	'invite_orderby_friend'	=> 'Arkada_ kategori',
	'invite_orderby_name'	=> 'Arkada_ ad+',
	'invite_send'	=> 'Davet Gönder',
	'invite_still_choose'	=> 'Kalanlar ',
	'selected'	=> 'Seçili',
	'unit'	=> ' ',
	'unselected'	=> 'Kalanlar',
	'preview_footertext'	=> 'Copyright and footer',
	'preview_highlightlink'	=> 'Highlight link',
	'preview_lighttext'	=> 'Hafif Text',
	'preview_link'	=> 'Link Text',
	'preview_midtext'	=> 'Orta Text',
	'preview_msg'	=> '<a href="javascript:;" class="lit">turkk.net</a> Community System(Abbreviation <stong class="xw1 xi1">Forum</stong>)is a PHP and MySQL system.',
	'preview_smalltext'	=> 'Mini Text',
	'preview_text'	=> 'Normal Text',
	'preview_threadtext'		=> 'Preview thread',//'-',
	'table_header'			=> 'Header',//'+',
	'album'	=> 'Alb_m',
	'article'	=> 'Makale',
	'blog'	=> 'Blog',
	'enter_content'	=> 'Anahtar kelimeler...',
	'hot_search'	=> 'S+cak Arama',
	'search_this_forum'	=> 'Arama ',
	'thread'	=> 'Konu',
	'users'	=> '_ye',
	'input_message1'	=> 'Toplam ',
	'input_message2'	=> 'karakter girebilirsiniz.',
	'report'	=> 'Uyar',
	'report_reason'	=> 'Neden',
	'seccode'	=> 'Kod',
	'seccode_change'	=> 'De_i_tir',
	'secqaa'	=> 'G_venlik S&C',
	'e_bold'	=> 'Bold',
	'e_code'	=> 'Kod',
	'e_forecolor'	=> 'Yaz+ Renk',
	'e_image'	=> 'Resim',
	'e_quote'	=> 'Al+nt+',
	'e_url'	=> 'URL Ekle',
	'attach_forward'	=> 'E_er y_kleme {$refreshsecond} saniye içersinde ba_lam+yorsa,l_tfen buraya t+klay+n',
	'board_message'	=> 'İpuçlar+',
	'cancel'	=> 'İptal',
	'message_closetime'		=> 'Seconds after the window closed',//'Ŧ',
	'message_forward'	=> 'Taray+c+n+z otomatik olarak yönlendiremiyorsa, l_tfen buraya t+klay+n',
	'message_go_back'	=> '[Geri dön]',
	'message_locationtime'		=> 'Seconds after the page jump',//'-',
	'basic_situation'	=> 'Basic Overview',
	'forum_stat'	=> 'Forum Stats',
	'manage_team'	=> 'Ekip',
	'member_list'	=> '_yeler',
	'mod_works'	=> 'Istatistikler',
	'stats'				=> 'Site statistics',//'¦',
	'trend'	=> 'Trends',
	'app_add'			=> 'Add application',
	'app_management'		=> 'Manage application',
	'e_audio'	=> 'M_zik',
	'e_audio_title'	=> 'M_zik Ekle',
	'e_autotypeset'	=> 'Oto',
	'e_center'	=> 'Ortala',
	'e_code_title'	=> 'Kod Ekle',
	'e_flash'	=> 'Flash',
	'e_flash_title'	=> 'Flash Ekle',
	'e_font'			=> 'Font',//'-',
	'e_fontname'	=> 'Font',
	'e_fontsize'	=> 'Yaz+ Boyut',
	'e_hr_title'	=> 'Yatay çizgi',
	'e_image_title'	=> 'Resim Ekle',
	'e_img_height'	=> 'Y_kseklik',
	'e_img_inserturl'	=> 'L_tfen resim URL giriniz',
	'e_img_width'	=> 'Geni_lik',
	'e_italic'	=> 'Italik',
	'e_left'	=> 'Sol',
	'e_orderedlist'	=> 'Dizili Liste',
	'e_paste'	=> 'Yap+_t+r',
	'e_quote_title'	=> 'Al+nt+ Ekle',
	'e_removeformat'	=> 'Format Kald+r',
	'e_right'	=> 'Sa_',
	'e_size'			=> 'Size',//'-',
	'e_smilies'	=> 'İfadeler',
	'e_smilies_title'	=> 'İfade Ekle',
	'e_table'	=> 'Tablo Ekle',
	'e_underline'	=> 'Altçizgi',
	'e_unlink'	=> 'URL Sil',
	'e_unorderedlist'	=> 'Dizinsiz Liste',
	'e_video'	=> 'Video',
	'e_video_title'	=> 'Video Ekle',
	'submit'	=> 'Tamam',
	'e_attach_del'	=> 'Sil',
	'e_attach_mediacode'	=> 'Medya kodu ekle',
	'e_attach_url'	=> 'Dosya URL ekle',
	'readperm'			=> 'Read Permission',//'',
	'update'	=> 'G_ncelle',
	'none_newthread'	=> 'Yeni mesaj bulunmuyor!',
	'author'	=> 'Yazan',
	'username'	=> '_ye',
	'more'	=> 'Devam',
	'publish'	=> 'Yay+nla',
	'delete'	=> 'Sil',
	'guest'				=> 'Guest',
	'upload'	=> 'Y_kle',
	'e_attach_insert'	=> 'Eklemek için dosyaya t+klay+n',
	'e_attach_inserturl'		=> ', &quot;attach://&quot; at the beginning of the attachment address support the download for anyone, please add carefully.',//', "attach://" -+-----',
	'e_img_albumlist'	=> 'Alb_m Resim',
	'e_img_attach'	=> 'Resimler',
	'e_img_insertphoto'	=> 'Eklemek için resme t+klay+n',
	'e_img_www'	=> 'Web Resim',
	'e_attach_title'	=> 'Dosya Ekle',
	'target_blank'			=> 'Open in a new window',//'--',
	'thread_activity'	=> 'Etkinlikler',
	'thread_debate'	=> 'Tart+_ma',
	'thread_reward'	=> '-d_ller',
	'thread_trade'	=> 'Ticaret',
	'edit'	=> 'Edit',
	'return'	=> 'Geridön',
	'discuzcode'	=> 'BBKod',
	'member'	=> '_ye',
	'panel_login'	=> 'Panel Login',
	'panel_login_password'	=> '_ifre',
	'panel_login_username'	=> '_ye',
	'panel_notice_login'	=> 'Yanl+_ _ifre girdi_iniz takdirde sistem 15 dakika boyunca kilitlenecektir.',
	'anonymous'	=> 'Anonim',
	'select_all'	=> 'Hepsi'
	'e_attach'	=> 'Dosya',
	'e_downremoteimg'		=> 'Download Image',//'---',
	'e_downremoteimg_title'		=> 'Download remote images',//'---',
	'e_free'	=> 'Free Bilgi',
	'e_hide'	=> 'Gizli Bilgi',
	'e_pasteword'			=> 'Paste from Word',//'Word -++',
	'e_pasteword_title'		=> 'Paste content from Word',//' Word -++',
	'smilies'	=> 'İfadeler',
	'uid'	=> '_ye N°',
	'recommend'			=> 'Recommend block',//'',
	'trade'	=> 'Ticaret',
	'manage'			=> 'Manage',//'',
	'not_enough'			=> 'Insufficient',//'',
	'moderate_need'			=> 'Pending',//'-',
	'portal'	=> 'Site',
	'reward_answer'	=> 'Cevap',
	'favorite'	=> 'Favoriler',
	'choose_please'	=> 'Seç',
	'create'	=> 'Ekle',
	'option_required'	=> 'Gerekli',
	'finished'	=> 'Completed',
	'ignore_all'	=> 'Hepsi İptal',
	'pass_all'	=> 'Pass all',
	'create_on'	=> 'Ekleme ',
	'add'	=> 'Ekle',
	'activity'	=> 'Etkinlikler',
	'blockdata_recommend'	=> 'Tavsiye',
	'share'	=> 'Payla_',
	'article_push'	=> 'Makale Push',
	'debate'	=> 'Tart+_malar',
	'doing'	=> 'Doing',
	'friends'	=> 'Arkada_lar',
	'online_member'			=> 'Online members',//'',
	'my_space'	=> '_ye Paneli',
	'magic'	=> 'Props',
	'medals'	=> 'Madalya',
	'task'	=> 'Görev',
	'notice'	=> ' Duyuru',
	'you'				=> 'You',//'',
	'poll'	=> 'Anketler',
	'group_expiry_type_ext'		=> 'Extended user group',//'-Ȭ',
	'reward'	=> '-d_ller',
	'task_done'	=> 'Tamamlananlar',
	'task_failed'	=> 'Ba_ar+s+z',
	'task_new'	=> 'Yeni',
	'task_admins'	=> 'Yöneticiler',
	'task_applicants'	=> 'Toplam $task[applicants] _ye bu görev için ba_vurmu_.',
	'task_applies_full'	=> 'Ba_vurular dolmu_tur.',//Modify
	'task_apply_condition'	=> 'Ko_ullar',
	'task_applyagain'	=> ' tekrar ba_vur',
	'task_applyagain_now'	=> 'Tekrar ba_vurabilirsiniz',
	'task_complete'	=> 'Tamamlanm+_',
	'task_complete_condition'	=> 'Görev tamamlama ko_ulu',
	'task_complete_on'	=> 'Tamamlama  ',
	'task_detail'	=> 'Görev Detaylar',
	'task_endtime'	=> 'Bu görev\'in biti_ tarihi: $task[endtime], bu tarih\'ten sonra ba_vuramazs+n+z',
	'task_general_users'	=> 'Genel _yeler',
	'task_group_nopermission'	=> '_ye grubunuzun bu görev için izni bulunmuyor.',
	'task_lose_on'	=> 'Vazgeçme  ',
	'task_numlimit'	=> 'Max ba_vuru',//modify
	'task_period_day'	=> 'Her $task[period] g_n\'de tekrar deneyebilirsiniz.',
	'task_period_hour'	=> 'Her $task[period] saat\'te tekrar deneyebilirsiniz.',
	'task_period_month'	=> 'Her $task[period] ay\'da tekrar deneyebilirsiniz.',
	'task_period_week'	=> 'Her $periodweek hafta\'da tekrar deneyebilirsiniz.',
	'task_reapply'	=> ' tekrar dene',
	'task_reapply_now'	=> 'Tekrar deneyebilirsiniz',
	'task_relatedtask'	=> 'Ilgili görevi tamamlamal+s+n+z',
	'task_reward'	=> '-d_ller',
	'task_applies'	=> 'Ba_vurma',
	'task_nodoing'	=> 'Ba_lad+_+n+z görev yok, yeni görevlere bak+n+z',
	'task_nonew'	=> 'Yeni görev bulunmuyor, daha sonra tekrar kontrol ediniz',
	'password_security'	=> '_ifre',
	'increase'			=> 'Increase',//'',
	'friend_top'			=> 'Friend Top List',//'',
	'connect_config_newpassword_comment'	=> 'You are currently use a QQ account was bind to the site. Here you can set up individual password, Only set up an independent password site to fill in the password so the corresponding function can use it',//'--QQϬ-------۬--',
	'email'	=> 'Email',
	'security_question'	=> 'Yoksa, geçiniz',
	'security_question_0'	=> 'G_venlik Sorusu',
	'security_question_1'	=> 'Anne ismi',
	'security_question_2'	=> 'Yemek ismi',
	'security_question_3'	=> 'Dede ismi',
	'security_question_4'	=> '_ansl+ say+n+z',
	'security_question_5'	=> 'Sevdi_iniz yemek',
	'security_question_6'	=> '-_retmeninizin ismi',
	'security_question_7'	=> 'Ilk sevgilinizin ismi',
	'group_expiry_time'	=> 'Geçerlilik',
	'login_id'	=> '_ye N°:',
	'login_password'	=> '_ifre:',
	'login_permanent'	=> 'Hat+rla?',
	'security_a'			=> 'Answer',//'',
	'security_q'	=> 'G_venlik Sorusu',
	'forgotpw'	=> '_ifremi Unuttum?',
	'image'	=> 'Resimler',
	'remote'	=> 'Remote',
	'credit_ranking'	=> 'Kredi S+ralama',
	'auction_ranking'	=> 'Auction Ranking',
	'close_ranking_note'	=> 'Administrator has closed auction,for the time being unable to continue ranking',
	'credit_is_not_number'	=> 'You fill in the {$extcredits[$creditid][title]}is not a legal value',
	'credit_title_error'	=> 'You fill in the{$extcredits[$creditid][title]}can not be less than 1',
	'credit_title_message'	=> 'Your current point {$extcredits[$creditid][title]}: "+maxCredit+",Please enter a number less than the value',
	'current_ranking'	=> 'G_ncel S+ralama',
	'friend_need_help'	=> 'Arkada_lara Yard+m',
	'friend_num_ranking'	=> 'Arkada_ S+ralama',
	'friend_top_note'	=> 'Duyuru Listesi',
	'handsel'	=> 'Hediye',
	'handsel_bid'	=> 'Gift auction',
	'help_friend_in_top'	=> 'Arkada_ S+ralama Yard+m',
	'i_ranking'	=> 'S+ralama',
	'increase_bid'	=> 'Increase bid',
	'make_persistent_efforts'	=> 'Make persistent efforts',
	'max_char_ranking'	=> 'Liste slogan için max 50 karakter giriniz ',
	'my_ranking_declaration'	=> 'Klasman Slogan+m',
	'not_exceed'	=> 'Do not exceed',
	'ranking_message_0'	=> 'Still have not ranking?Ranking it yourself, which will greatly enhance the visibility of your home.',
	'ranking_message_1'	=> 'Bidding ($extcredits[$ creditid][title]) more,xxposure of your home will be higher;',
	'ranking_message_2'	=> 'Ranking user home page is another effective browsing time,its bid {$extcredits[$creditid][title]}will be reduced by',
	'self_current_credit'	=> 'Mevcut puan',
	'self_current_friend_num'	=> 'Geçerli arkada_ say+s+',
	'top_100_update'	=> 'The following list ranks the top 100 for the data for every $cache_time minute.',
	'your_current_bid'	=> 'Your current bid',
	'top_orderby_blogs'		=> 'by number of blogs',//'-',
	'top_orderby_credits'		=> 'by number of points',//'-',
	'top_orderby_posts'		=> 'by number of posts',//'-',
	'top_orderby_uid'		=> 'by registration time',//'צ+',

//---------------------------
// Added by Valery Votintsev

//static/space/t1/style.css
	'default_style'	=> 'Default style',//'[name]-[/name]',

//---------------------------
//static/space/t2/style.css
	'nature'	=> 'Nature',//'[name]Ħ[/name]',

//---------------------------
//static/space/t3/style.css
	'sky'		=> 'Sky',//'[name][/name]',

//---------------------------
//static/space/t4/style.css
	'cat'		=> 'Cat',//'[name][/name]',

//---------------------------
//static/space/t5/style.css
	'courtyard'	=> 'Courtyard',//'[name][/name]',

//---------------------------
//static/space/t6/style.css
	'green_wall'	=> 'Green Wall',//'[name][/name]',

//---------------------------
//static/space/t7/style.css
	'cowboy'	=> 'Cowboy',//'[name][/name]',

//---------------------------
//static/space/t8/style.css
	'christmas'	=> 'Christmas',//'[name][/name]',

//---------------------------
//static/topic/t1/style.css
	'default_skin'	=> 'Default Skin',//'[name][/name]',

//---------------------------
//static/topic/t2/style.css
	'skin_2'	=> 'Skin 2',//'[name]2[/name]',

//---------------------------
//Change Language
	'change_language'	=> 'Change language',

//vot:
	'new'		=> 'New',//'-',

//---------------------------
//vot: Titles from install_var.php, pre_common_nav table

	'register'	=> 'Register',//'',

	'nav_1'		=> 'Portal',//'Ȭ',//1,
	'nav_2'		=> 'Forum',//'',//2,
	'nav_3'		=> 'Groups',//'-',//3,
	'nav_4'		=> 'Space',//'',//4,
	'nav_5'		=> 'Applications',//'',//5,
	'nav_6'		=> 'Plugins',//'',//6,
	'nav_7'		=> 'Help',//'',//7,
	'nav_8'		=> 'RankList',//'',//8,
	'nav_stat'	=> 'Statistics',//'¦',
	'nav_report'	=> 'Reports',//'-',
	'nav_archiver'	=> 'Archive',
	'nav_mobile'	=> 'Mobile',//'ܦ',
	'nav_blog'	=> 'Blogs',//'',
	'nav_album'	=> 'Albums',//'۬',
	'nav_share'	=> 'Shares',//'',
	'nav_doing'	=> 'Doings',//'--',
	'nav_friend'	=> 'Friends',//'-',
	'nav_thread'	=> 'Threads',//'',
	'nav_favorite'	=> 'Favorites',//'Ԧ',
	'nav_magic'	=> 'Magic',//'Ŭ',
	'nav_medal'	=> 'Medals',//'',
	'nav_task'	=> 'Tasks',//'',
	'nav_sethomepage'	=> 'Set as Homepage',//'-',
	'nav_setfavorite'	=> 'Add to Favorites',//'Ԧ',
//	'nav_'		=> '',//'',

/* Obsolete
	'space_short'	=> 'Ortam',
	'morethread'	=> 'Devam',
	'task_unfinish'	=> 'Görev tamamlanamamış.',
	'user_center'	=> 'Üye Panel',
	'user_index'	=> 'Profil Sayfa',
	'manager'	=> 'Manager',//Modify
	'administrator'	=> 'Admin',
	'contactus'	=> 'İletişim',
	'thread_rewardend'	=> 'Çözülmüş',
	'setup'	=> 'Ayarlar',
	'batch'	=> 'Toplu',
	'task_complete_time_start'	=> 'Task start time from the application,',//Modify
	'task_complete_time_limit'	=> ' $taskvars[complete][time][value] saat içersinde, ',
	'task_complete_act_buddy'	=> ' $taskvars[complete][num][value] arkadaş ekle.',
	'task_complete_act_favorite'	=> ' $taskvars[complete][num][value] konu favorile.',
	'task_complete_act_magic'	=> 'use props $taskvars[complete][num][value] times.',
	'task_complete_forumid'	=> 'forum\'a git <a href="forum.php?mod=forumdisplay&fid=$taskvars[complete][forumid][value]" target="_blank">{$_G[cache][forums][$taskvars[complete][forumid][value]][name]}</a> and ',
	'task_complete_act_newthread'	=> ' $taskvars[complete][num][value] yeni konu yaz.',
	'task_complete_act_newpost'	=> 'yeni konu yaz veya $taskvars[complete][num][value] yeni cevap ekle.',
	'task_complete_act_newreply_thread'	=> ' "<a href="forum.php?mod=viewthread&tid=$taskvars[complete][threadid][value]" target="_blank">$subject</a>" konusuna $taskvars[complete][num][value] cevap ekle.',
	'task_complete_act_newreply_author'	=> ' "<a href="home.php?mod=space&uid=$taskvars[complete][authorid][value]" target="_blank">$author</a>"\'n konusuna $taskvars[complete][num][value] tane cevap ekle.',
	'faq_search'	=> 'Arama SSS',
	'faq_search_title_and_content'	=> 'Search FAQ title and content',
	'faq_search_title'	=> 'SSS başlık arama',
	'faq_search_content'	=> 'Search FAQ content',
	'faq_related'	=> 'İlgili SSS',
	'e_hr'	=> 'Yatay çizgi ekle',
	'e_strike'	=> 'Ara çizgi ekle',
	'e_bold_title'	=> 'Bold',
	'e_italic_title'	=> 'Italik',
	'e_underline_title'	=> 'Altçizgi',
	'e_strike_title'	=> 'Araçizgi',
	'e_paragraph'	=> 'Paragraf',
	'e_floatleft'	=> 'Sola Kaydır',
	'e_floatright'	=> 'Sağa Kaydır',
	'e_list'	=> 'Liste',
	'e_contract'	=> 'Daralt',
	'e_expand'	=> 'Genişlet',
	'e_email'	=> 'Email Ekle',
	'e_img_local'	=> 'Resim Ekle',
	'e_img_album'	=> 'Albümüm',
	'seccode_comment'	=> 'Lürfen kodu giriniz',
	'secqaa_comment'	=> 'Lütfen soruyu cevaplayınız:',
	'register_profile_seccode_invalid'	=> 'Güvenlik kodu hatası.',
	'register_profile_secqaa_invalid'	=> 'Güvenlik cevap hatası.',
	'search_friends'	=> 'Arkadaş Arama',
	'new_message'	=> 'Yeni Mesaj',
	'recent_contacts'	=> 'Son İletişim',
	'group'	=> 'Gruplar',
	'launch'	=> 'Mesajlar',
	'sale'	=> 'Post',
	'task'	=> 'Görevler',
	'no_login'	=> 'Giriş yapınız',
	'favorite'	=> 'Favoriler',
	'fourm'	=> 'Forum',
	'qmenu_register'	=> 'Kayıt',
	'styleswitch'	=> 'Stil',
	'report_current_page'	=> 'Uyar',
	'userabout_thread'	=> 'Konular',
	'preview_navcur'	=> 'Geçerli',
	'preview_inputtext'	=> 'It\'s a input box',
	'preview_nav'	=> 'Men_',
	'header_savecache'	=> 'Saved temporarily',
	'header_savecache_desc'	=> 'Save your DIY data temporarily, you can continue next time',
	'header_savecachemsg'	=> 'Page temporary saved',
	'header_tabframe'	=> 'Table frame',
	'this_forum'	=> 'Bu Forum',
	'search_user'	=> 'Üye Arama',
	'advanced_search'	=> 'Gelişmiş',
	'prompt'	=> 'Ipuçları',
	'my_center'	=> 'Panel',
	'modify_avatar'	=> 'Avatar',
	'personal_profile'	=> 'Profil',
	'privacy_filter'	=> 'Gizlilik',
	'group_expiry_type'	=> 'Type',
	'group_expiry_type_main'	=> 'Primary usergroup',
*/

);

?>